# Copyright 2013 Google Inc. All Rights Reserved.
#
# Description:
#  mdns server and client

licenses(["notice"])  # New BSD

exports_files(["LICENSE"])

package(default_visibility = ["//visibility:public"])
